exports.seed = async function (knex) {
  await knex('users').del();

  const now = knex.fn.now();

  await knex('users').insert([
    {
      id: 1,
      initials: 'J.',
      first_name: 'Jetze',
      infix: null,
      last_name: 'Kempenaar',
      partner_infix: null,
      partner_last_name: null,
      name_usage: 'eigennaam',
      date_of_birth: '1975-04-12',
      place_of_birth: 'Amsterdam',
      date_of_death: null,
      place_of_death: null,
      street_name: 'Leliegracht',
      house_number: '415',
      house_letter: null,
      house_number_addition: null,
      zip_code: '3129 AB',
      city: 'Amsterdam',
      email: 'j.kempenaar@kerkrentmeester.nl',
      email_verified_at: '2026-03-01 09:00:00',
      phone_number: '+31622549453',
      mobile_number: '+31622549453',
      profile_picture_url: '\\images\\users\\jetzekempenaar.jpg',
      relation_to_deceased: null,
      position: 'Kerkrentmeester',
      password_hash: null,
      remember_token: null,
      created_at: now,
      updated_at: now
    },

    {
      id: 2,
      initials: 'B. C. M.',
      first_name: 'Bea',
      infix: null,
      last_name: 'Bakker',
      partner_infix: null,
      partner_last_name: null,
      name_usage: 'eigennaam',
      date_of_birth: '1982-09-03',
      place_of_birth: 'Amsterdam',
      date_of_death: null,
      place_of_death: null,
      street_name: 'Vondelpark',
      house_number: '777',
      house_letter: 'A',
      house_number_addition: null,
      zip_code: '2348 GJ',
      city: 'Amsterdam',
      email: 'beabakkerr@gmail.com',
      email_verified_at: '2026-03-02 10:00:00',
      phone_number: '+31622345453',
      mobile_number: '+31622345453',
      profile_picture_url: null,
      relation_to_deceased: null,
      position: null,
      password_hash: null,
      remember_token: null,
      created_at: now,
      updated_at: now
    },

    {
      id: 3,
      initials: 'L.',
      first_name: 'Liza',
      infix: null,
      last_name: 'Petrushenko',
      partner_infix: 'van',
      partner_last_name: 'Vliet',
      name_usage: 'eigennaam_partnernaam',
      date_of_birth: '1995-11-25',
      place_of_birth: 'Kyiv',
      date_of_death: null,
      place_of_death: null,
      street_name: 'Bloemgracht',
      house_number: '390',
      house_letter: null,
      house_number_addition: 'bis',
      zip_code: '3467 JH',
      city: 'Amsterdam',
      email: 'liza2511liza@gmail.com',
      email_verified_at: null,
      phone_number: '+31643542153',
      mobile_number: '+31643542153',
      profile_picture_url: null,
      relation_to_deceased: 'Geen',
      position: null,
      password_hash: null,
      remember_token: null,
      created_at: now,
      updated_at: now
    },

    {
      id: 4,
      initials: 'Y.',
      first_name: 'Yassira',
      infix: null,
      last_name: 'Raddahi',
      partner_infix: null,
      partner_last_name: null,
      name_usage: 'eigennaam',
      date_of_birth: '2002-10-19',
      place_of_birth: 'Zwolle',
      date_of_death: null,
      place_of_death: null,
      street_name: 'Egelantiersgracht',
      house_number: '401',
      house_letter: null,
      house_number_addition: null,
      zip_code: '2349 OV',
      city: 'Amsterdam',
      email: 'yassiraraddahi@gmail.com',
      email_verified_at: null,
      phone_number: '+31698499433',
      mobile_number: '+31698499433',
      profile_picture_url: null,
      relation_to_deceased: 'nicht',
      position: null,
      password_hash: null,
      remember_token: null,
      created_at: now,
      updated_at: now
    },

    {
      id: 5,
      initials: 'B.',
      first_name: 'Bram',
      infix: null,
      last_name: 'Meijer',
      partner_infix: null,
      partner_last_name: 'Super Sus',
      name_usage: 'partnernaam',
      date_of_birth: '2000-01-16',
      place_of_birth: 'Dwingeloo',
      date_of_death: null,
      place_of_death: null,
      street_name: 'Lheebroek',
      house_number: '27',
      house_letter: null,
      house_number_addition: null,
      zip_code: '8923 HF',
      city: 'Dwingeloo',
      email: 'brammeijer16@hotmail.com',
      email_verified_at: null,
      phone_number: '0612139396',
      mobile_number: '0612139396',
      profile_picture_url: null,
      relation_to_deceased: null,
      position: null,
      password_hash: null,
      remember_token: null,
      created_at: now,
      updated_at: now
    },

    {
      id: 6,
      initials: 'L.',
      first_name: 'Lisa',
      infix: 'de',
      last_name: 'Vries',
      partner_infix: null,
      partner_last_name: null,
      name_usage: 'eigennaam',
      date_of_birth: '1988-02-14',
      place_of_birth: 'Utrecht',
      date_of_death: null,
      place_of_death: null,
      street_name: 'Keizersgracht',
      house_number: '45',
      house_letter: null,
      house_number_addition: null,
      zip_code: '4389 YJ',
      city: 'Amsterdam',
      email: 'lisa.devries@gmail.com',
      email_verified_at: null,
      phone_number: '0612345678',
      mobile_number: '0612345678',
      profile_picture_url: null,
      relation_to_deceased: null,
      position: null,
      password_hash: null,
      remember_token: null,
      created_at: now,
      updated_at: now
    },

    {
      id: 7,
      initials: 'T.',
      first_name: 'Thomas',
      infix: 'van den',
      last_name: 'Berg',
      partner_infix: null,
      partner_last_name: null,
      name_usage: 'eigennaam',
      date_of_birth: '1985-06-30',
      place_of_birth: 'Utrecht',
      date_of_death: null,
      place_of_death: null,
      street_name: 'Wilhelminastraat',
      house_number: '12',
      house_letter: null,
      house_number_addition: null,
      zip_code: '6679 TK',
      city: 'Utrecht',
      email: 'thomas.vdberg@outlook.com',
      email_verified_at: null,
      phone_number: '0687654321',
      mobile_number: '0687654321',
      profile_picture_url: null,
      relation_to_deceased: null,
      position: null,
      password_hash: null,
      remember_token: null,
      created_at: now,
      updated_at: now
    },

    {
      id: 8,
      initials: 'J.',
      first_name: 'Jan',
      infix: 'de',
      last_name: 'Vries',
      partner_infix: null,
      partner_last_name: null,
      name_usage: 'eigennaam',
      date_of_birth: '1960-01-10',
      place_of_birth: 'Zwolle',
      date_of_death: null,
      place_of_death: null,
      street_name: 'Kerkstraat',
      house_number: '12',
      house_letter: null,
      house_number_addition: null,
      zip_code: '8011 AA',
      city: 'Zwolle',
      email: 'jan.devries@email.nl',
      email_verified_at: '2026-03-17 10:39:11',
      phone_number: '0612345678',
      mobile_number: '0612345678',
      profile_picture_url: null,
      relation_to_deceased: null,
      position: null,
      password_hash: null,
      remember_token: null,
      created_at: now,
      updated_at: now
    },

    {
      id: 9,
      initials: 'S.',
      first_name: 'Sanne',
      infix: null,
      last_name: 'Jansen',
      partner_infix: null,
      partner_last_name: null,
      name_usage: 'eigennaam',
      date_of_birth: '1992-04-11',
      place_of_birth: 'Zwolle',
      date_of_death: null,
      place_of_death: null,
      street_name: 'Meppelerstraatweg',
      house_number: '45',
      house_letter: null,
      house_number_addition: null,
      zip_code: '8014 RT',
      city: 'Zwolle',
      email: 'sanne.jansen@email.nl',
      email_verified_at: '2026-03-17 10:39:11',
      phone_number: '0687654321',
      mobile_number: '0687654321',
      profile_picture_url: null,
      relation_to_deceased: null,
      position: null,
      password_hash: null,
      remember_token: null,
      created_at: now,
      updated_at: now
    },

    {
      id: 10,
      initials: 'M.',
      first_name: 'Mohammed',
      infix: 'el',
      last_name: 'Amrani',
      partner_infix: null,
      partner_last_name: null,
      name_usage: 'eigennaam',
      date_of_birth: '1987-12-08',
      place_of_birth: 'Zwolle',
      date_of_death: null,
      place_of_death: null,
      street_name: 'Assendorperstraat',
      house_number: '88',
      house_letter: null,
      house_number_addition: null,
      zip_code: '8012 DE',
      city: 'Zwolle',
      email: 'm.elamrani@email.nl',
      email_verified_at: '2026-03-17 10:39:11',
      phone_number: '0611223344',
      mobile_number: '0611223344',
      profile_picture_url: null,
      relation_to_deceased: null,
      position: null,
      password_hash: null,
      remember_token: null,
      created_at: now,
      updated_at: now
    },

    {
      id: 11,
      initials: 'L.',
      first_name: 'Lisa',
      infix: 'van',
      last_name: 'Dijk',
      partner_infix: null,
      partner_last_name: null,
      name_usage: 'eigennaam',
      date_of_birth: '1990-09-21',
      place_of_birth: 'Zwolle',
      date_of_death: null,
      place_of_death: null,
      street_name: 'Holtenbroekerdijk',
      house_number: '23',
      house_letter: null,
      house_number_addition: null,
      zip_code: '8031 LH',
      city: 'Zwolle',
      email: 'lisa.vandijk@email.nl',
      email_verified_at: '2026-03-17 10:39:11',
      phone_number: '0622334455',
      mobile_number: '0622334455',
      profile_picture_url: null,
      relation_to_deceased: null,
      position: null,
      password_hash: null,
      remember_token: null,
      created_at: now,
      updated_at: now
    },

    {
      id: 12,
      initials: 'P.',
      first_name: 'Peter',
      infix: null,
      last_name: 'Bakker',
      partner_infix: null,
      partner_last_name: null,
      name_usage: 'eigennaam',
      date_of_birth: '1955-02-17',
      place_of_birth: 'Zwolle',
      date_of_death: null,
      place_of_death: null,
      street_name: 'Zwartewaterallee',
      house_number: '101',
      house_letter: null,
      house_number_addition: null,
      zip_code: '8031 DX',
      city: 'Zwolle',
      email: 'peter.bakker@email.nl',
      email_verified_at: '2026-03-17 10:39:11',
      phone_number: '0633445566',
      mobile_number: '0633445566',
      profile_picture_url: null,
      relation_to_deceased: null,
      position: null,
      password_hash: null,
      remember_token: null,
      created_at: now,
      updated_at: now
    },

    {
      id: 13,
      initials: 'F.',
      first_name: 'Fatima',
      infix: null,
      last_name: 'Hassan',
      partner_infix: null,
      partner_last_name: null,
      name_usage: 'eigennaam',
      date_of_birth: '1978-08-05',
      place_of_birth: 'Zwolle',
      date_of_death: null,
      place_of_death: null,
      street_name: 'Hogenkampsweg',
      house_number: '67',
      house_letter: null,
      house_number_addition: null,
      zip_code: '8022 DA',
      city: 'Zwolle',
      email: 'fatima.hassan@email.nl',
      email_verified_at: '2026-03-17 10:39:11',
      phone_number: '0644556677',
      mobile_number: '0644556677',
      profile_picture_url: null,
      relation_to_deceased: null,
      position: null,
      password_hash: null,
      remember_token: null,
      created_at: now,
      updated_at: now
    },

    {
      id: 14,
      initials: 'T.',
      first_name: 'Tom',
      infix: 'van der',
      last_name: 'Meer',
      partner_infix: null,
      partner_last_name: null,
      name_usage: 'eigennaam',
      date_of_birth: '1989-11-13',
      place_of_birth: 'Zwolle',
      date_of_death: null,
      place_of_death: null,
      street_name: 'Bachlaan',
      house_number: '9',
      house_letter: null,
      house_number_addition: null,
      zip_code: '8031 HL',
      city: 'Zwolle',
      email: 'tom.vandermeer@email.nl',
      email_verified_at: '2026-03-17 10:39:11',
      phone_number: '0655667788',
      mobile_number: '0655667788',
      profile_picture_url: null,
      relation_to_deceased: null,
      position: null,
      password_hash: null,
      remember_token: null,
      created_at: now,
      updated_at: now
    },

    {
      id: 15,
      initials: 'E.',
      first_name: 'Emma',
      infix: null,
      last_name: 'Smit',
      partner_infix: null,
      partner_last_name: null,
      name_usage: 'eigennaam',
      date_of_birth: '2001-03-29',
      place_of_birth: 'Zwolle',
      date_of_death: null,
      place_of_death: null,
      street_name: 'Veerallee',
      house_number: '55',
      house_letter: null,
      house_number_addition: null,
      zip_code: '8019 AA',
      city: 'Zwolle',
      email: 'emma.smit@email.nl',
      email_verified_at: '2026-03-17 10:39:11',
      phone_number: '0666778899',
      mobile_number: '0666778899',
      profile_picture_url: null,
      relation_to_deceased: null,
      position: null,
      password_hash: null,
      remember_token: null,
      created_at: now,
      updated_at: now
    },

    {
      id: 16,
      initials: 'O.',
      first_name: 'Olivier',
      infix: null,
      last_name: 'Testman',
      partner_infix: null,
      partner_last_name: null,
      name_usage: 'eigennaam',
      date_of_birth: '1993-05-10',
      place_of_birth: 'Zwolle',
      date_of_death: null,
      place_of_death: null,
      street_name: 'Teststraat',
      house_number: '1',
      house_letter: null,
      house_number_addition: null,
      zip_code: '8000 AA',
      city: 'Zwolle',
      email: 'olivier.test@email.nl',
      email_verified_at: null,
      phone_number: '0677777777',
      mobile_number: '0677777777',
      profile_picture_url: null,
      relation_to_deceased: null,
      position: null,
      password_hash: null,
      remember_token: null,
      created_at: now,
      updated_at: now
    }
  ]);
};
