exports.seed = async function (knex) {
  await knex('cemeteries').del();
  await knex('cemeteries').insert([
    {
      name: 'Kerkhof Kranenburg',
      street_name: 'Kranenburgweg',
      house_number: '7',
      house_letter: null,
      house_number_addition: null,
      zip_code: '8024 AC',
      city: 'Zwolle',
      email: 'info.kranenburg@cemetery.nl',
      phone_number: '038 454 4148',
      iban_iv: null,
      iban_encrypted: null,
      website_url: 'https://www.zwolle.nl/begraven-en-cremeren-op-kranenburg',
      remarks: 'Kranenburg is een begraafplaats in het zuiden van Zwolle, gelegen aan de Kranenburgweg. De begraafplaats is in 1913 geopend en heeft een oppervlakte van ongeveer 10 hectare. Kranenburg biedt plaats aan ongeveer 10.000 graven en heeft een crematorium op het terrein. De begraafplaats is prachtig aangelegd met veel groen en bomen, en er zijn verschillende monumenten en grafkelders te vinden. Kranenburg is een rustige en serene plek waar mensen hun dierbaren kunnen herdenken en eren.',
      municipality_id: 1 },
    {  
      name: 'Kerkhof Meppelerstraatweg',
      street_name: 'Meppelerstraatweg',
      house_number: null,
      house_letter: null,
      house_number_addition: null,
      zip_code: '8014 RT', city: 'Zwolle',
      email: 'info.meppeler@cemetery.nl',
      iban_iv: null,
      iban_encrypted: null,
      website_url: 'https://www.zwolle.nl',
      remarks: 'Meppelerstraatweg is een begraafplaats in het oosten van Zwolle, gelegen aan de Meppelerstraatweg. De begraafplaats is in 1913 geopend en heeft een oppervlakte van ongeveer 10 hectare. Meppelerstraatweg biedt plaats aan ongeveer 10.000 graven en heeft een crematorium op het terrein. De begraafplaats is prachtig aangelegd met veel groen en bomen, en er zijn verschillende monumenten en grafkelders te vinden. Meppelerstraatweg is een rustige en serene plek waar mensen hun dierbaren kunnen herdenken en eren.',
      municipality_id: 1
    },
    {
      name: 'Kerkhof Voorst',
      street_name: 'Ridder Zwederlaan',
      house_number: '1',
      house_letter: 'A',
      house_number_addition: null,
      zip_code: '8042 CC', city: 'Zwolle',
      email: 'contact.voorst@cemetery.nl',
      iban_iv: null,
      iban_encrypted: null,
      municipality_id: 1
    },
    {
      name: 'Kerkhof Windesheim',
      street_name: 'Pastorieweg',
      house_number: null,
      house_letter: null,
      house_number_addition: null,
      zip_code: '8015 PK',
      city: 'Zwolle',
      email: 'beheer.windesheim@cemetery.nl',
      iban_iv: null,
      iban_encrypted: null,
      municipality_id: 1
    },
    {
      name: 'Kerkhof Bergklooster',
      street_name: 'Bergkloosterweg',
      house_number: '92',
      house_letter: null,
      house_number_addition: null,
      zip_code: '8034 PL',
      city: 'Zeist',
      email: 'info@bergklooster.nl',
      phone_number: '+31384532281',
      iban_iv: null,
      iban_encrypted: null,
      website_url: 'http://www.bergklooster.nl',
      municipality_id: 1
    },
    {
      name: 'R.K. Kerkhof Zwolle',
      street_name: 'Bisschop Willebrandlaan',
      house_number: '62',
      house_letter: null,
      house_number_addition: null,
      zip_code: '8021 GA',
      city: 'Zwolle',
      email: 'admin.rkkerkhof@cemetery.nl',
      phone_number: '+31384533853',
      iban_iv: null,
      iban_encrypted: null,
      website_url: 'https://www.rkkerkhofzwolle.nl',
      municipality_id: 1
    },
    {
      name: 'Kerkhof Kuyerhuislaan',
      street_name: 'Kuyerhuislaan',
      house_number: '16',
      house_letter: null,
      house_number_addition: null,
      zip_code: '8025 AS',
      city: 'Zwolle',
      email: 'info.joods@cemetery.nl',
      iban_iv: null,
      iban_encrypted: null,
      remarks: 'Kuyerhuislaan is een Joodse begraafplaats in het noorden van Zwolle, gelegen aan de Kuyerhuislaan. De begraafplaats is in 1890 geopend en heeft een oppervlakte van ongeveer 1 hectare. Kuyerhuislaan biedt plaats aan ongeveer 1.000 graven en heeft geen crematorium op het terrein. De begraafplaats is prachtig aangelegd met veel groen en bomen, en er zijn verschillende monumenten en grafkelders te vinden. Kuyerhuislaan is een rustige en serene plek waar mensen hun dierbaren kunnen herdenken en eren.',
      municipality_id: 1
    },
    {
      name: 'Kerkhof Het Heilige Kruis',
      street_name: 'Buitengasthuisstraat',
      house_number: null,
      house_letter: null,
      house_number_addition: null,
      zip_code: '8011 AG',
      city: 'Delft',
      email: 'contact.kruis@cemetery.nl',
      iban_iv: null,
      iban_encrypted: null,
      remarks: 'Het Heilige Kruis is een begraafplaats in Delft, gelegen aan de Buitengasthuisstraat. De begraafplaats is in 1950 geopend en heeft een oppervlakte van ongeveer 2 hectare. Het Heilige Kruis biedt plaats aan ongeveer 2.000 graven en heeft geen crematorium op het terrein. De begraafplaats is prachtig aangelegd met veel groen en bomen, en er zijn verschillende monumenten en grafkelders te vinden. Het Heilige Kruis is een rustige en serene plek waar mensen hun dierbaren kunnen herdenken en eren.',
      municipality_id: 1
    },
  ]);
};