exports.seed = async function (knex) {
  await knex("grave_tariffs").del();
  await knex("grave_tariffs").insert([
    {
      id: 1,
      cemetery_id: 1,
      contract_type: "eerste uitgifte",
      sort: "dubbel graf",
      duration_years: 20,
      burial_right: 1200.0,
      maintenance: 400.0,
      additional_interment: 250.0,
      valid_from_year: 2024,
      valid_to_year: null,
    },
    {
      id: 2,
      cemetery_id: 1,
      contract_type: "verlenging",
      sort: "dubbel graf",
      duration_years: 10,
      burial_right: 700.0,
      maintenance: 300.0,
      additional_interment: 250.0,
      valid_from_year: 2024,
      valid_to_year: null,
    },
    {
      id: 3,
      cemetery_id: 1,
      contract_type: "onbepaalde tijd",
      sort: null,
      duration_years: null,
      burial_right: 3500.0,
      maintenance: 0.0,
      additional_interment: 0.0,
      valid_from_year: 2024,
      valid_to_year: null,
    },
    {
      id: 4,
      cemetery_id: 5,
      contract_type: "eerste uitgifte",
      sort: "urnengraf",
      duration_years: 10,
      burial_right: 600.0,
      maintenance: 200.0,
      additional_interment: 0.0,
      valid_from_year: 2024,
      valid_to_year: null,
    },
    {
      id: 5,
      cemetery_id: 5,
      contract_type: "eerste uitgifte",
      sort: "kindergraf",
      duration_years: 20,
      burial_right: 400.0,
      maintenance: 150.0,
      additional_interment: 0.0,
      valid_from_year: 2024,
      valid_to_year: null,
    },
    {
      id: 6,
      cemetery_id: 8,
      contract_type: "eerste uitgifte",
      sort: "dubbel graf",
      duration_years: 20,
      burial_right: 900.0,
      maintenance: 350.0,
      additional_interment: 200.0,
      valid_from_year: 2010,
      valid_to_year: 2023,
    },
    {
      id: 7,
      cemetery_id: 8,
      contract_type: "verlenging",
      sort: "dubbel graf",
      duration_years: 10,
      burial_right: 700.0,
      maintenance: 300.0,
      additional_interment: 250.0,
      valid_from_year: 2024,
      valid_to_year: null,
    },
  ]);
};
