name: Deploy to kerkhovenbeheer.nl

on:
  push:
    branches:
      - main
      - develop
      
    paths:
      - 'apps/web/**'
      - 'apps/api/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Code ophalen
      - name: Checkout code
        uses: actions/checkout@v4

      # Node setup
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Build frontend
      - name: Install & build frontend
        working-directory: apps/web
        run: |
          npm ci
          npx vite build

      # Upload frontend
      - name: Upload frontend
        uses: appleboy/scp-action@v0.1.7
        with:
          host: kerkhovenbeheer.nl
          username: deb2004916
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "apps/web/dist/*"
          target: "/home/deb2004916/domains/kerkhovenbeheer.nl/public_html"

          
      # Create restart trigger (nieuw bestand)
      - name: Create restart file
        run: |
          mkdir -p apps/api/tmp
          date > apps/api/tmp/restart.txt


      # Upload API
      - name: Upload API
        uses: appleboy/scp-action@v0.1.7
        with:
          host: kerkhovenbeheer.nl
          username: deb2004916
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "apps/api/*"
          target: "/home/deb2004916/domains/api.kerkhovenbeheer.nl"
          strip_components: 2